name: Release

on:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  packages: write
  contents: write
  pull-requests: write

defaults:
  run:
    shell: bash

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      -   uses: googleapis/release-please-action@v4
          id: release
          with:
            token: ${{ secrets.GITHUB_TOKEN }}

      - uses: tada5hi/hevi-action@v1
        if: steps.release.outputs.releases_created == 'true'
        with:
          commit: TRUE
          push: FALSE
          directory: helm
          version: ${{ steps.release.outputs['major'] }}.${{ steps.release.outputs['minor'] }}.${{ steps.release.outputs['patch'] }}

      - name: Run chart-releaser
        if: steps.release.outputs.releases_created == 'true'
        uses: helm/chart-releaser-action@v1.7.0
        env:
          skip_existing: false
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"